# Welcome to Jekyll!
# This config file sets up your academicpages site.

# ====================================================
# Site Settings
# ====================================================
locale                   : "en-US"
title                    : "Iosif Pintirishis"
title_separator          : "-"
name                     : &name "Iosif Pintirishis"
description              : &description "personal description"
url                      : "https://josephpintirishis.github.io"
baseurl                  : "" # leave empty for user.github.io site
repository               : "JosephPintirishis/josephpintirishis.github.io"

# ====================================================
# Theme
# ====================================================
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  # - jekyll-feed
  - jekyll-redirect-from
  - jemoji

# ====================================================
# Author Information
# ====================================================
author:
  name             : "Iosif Pintirishis"
  avatar           : "webpage_profile.jpg"
  bio              : "Ph.D. student in Statistics and Computer Science"
  location         : "Milan, Italy"
  email            : "iosif.pintirishis@phd.unibocconi.it"
  github           : "JosephPintirishis"
  linkedin         : "iosif-pintirishis-a69387244"
  # add other profiles if you like (researchgate, scholar, etc.)

# ====================================================
# Social Sharing / SEO
# ====================================================
# twitter:
#  username: ""
# og_image: ""   # Optional: add a default social sharing image

# ====================================================
# Reading / Conversion Settings
# ====================================================
include:
  - .htaccess
  - _pages
  - files

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - tmp

markdown: kramdown
highlighter: rouge
encoding: "utf-8"

# ====================================================
# Collections
# ====================================================
collections:
  teaching:
    output: false
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# ====================================================
# Defaults
# ====================================================
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# ====================================================
# Sass/SCSS
# ====================================================
sass:
  sass_dir: _sass
  style: compressed

# ====================================================
# Archives
# ====================================================
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# ====================================================
# HTML Compression
# ====================================================
compress_html:
  clippings: all
  ignore:
    envs: development
